tasks:
- init: ./gradlew bootJar
  command:
    - |
        if [ -z ${ADYEN_HMAC_KEY+x} ]; then
            echo "ADYEN_HMAC_KEY environment variable not found. Please set environment variables and rerun session https://gitpod.io/variables."
        else
            ./gradlew bootRun
        fi

# exposed ports
ports:
- port: 8080
  onOpen: open-preview

vscode:
  extensions:
    - redhat.java
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-test
    - pivotal.vscode-spring-boot
